import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import { useRouter,  } from 'next/router';
import queryString from "query-string";

const MengundangPage = () => {
  const router = useRouter();
  const query = router.query = queryString.parse(router.asPath.split(/\?/)[1]); // Destructuring our router object
  const name = query['name'];
  // console.log('asd', router)
  // console.log('asdf', name)
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {name ? (
          <h1 className={styles.title}>
            Wedding<br/>
            Vivi Febriyani A & Zikri Ramdani<br/><br/>
            <small>Turut mengundang:</small><br/>
            {name}
            <br/>Di<br/>
            Tempat
          </h1>
        ) : (
          <h1 className={styles.title}>
            Wedding<br/>
            Vivi Febriyani A & Zikri Ramdani
          </h1>
        )}
        
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          rel="noopener noreferrer"
        >
          Powered by Zikri Ramdani
        </a>
      </footer>
    </div>
  )
}

export default MengundangPage;